version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/hbnb
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hbnb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
