"""Update all models

Revision ID: 611cd0717b85
Revises: 
Create Date: 2024-06-27 21:48:47.018454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611cd0717b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
