"""Update some models and routes

Revision ID: 854a9f8eb969
Revises: af60d97fa145
Create Date: 2024-06-28 14:01:17.502599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854a9f8eb969'
down_revision = 'af60d97fa145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cities_country_code', type_='foreignkey')
        batch_op.create_foreign_key('fk_cities_country_code', 'countries', ['country_code'], ['code'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint('fk_reviews_host_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_user_id', 'users', ['user_id'], ['id'])
        batch_op.drop_column('host_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint('fk_reviews_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_host_id', 'users', ['host_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cities_country_code', type_='foreignkey')
        batch_op.create_foreign_key('fk_cities_country_code', 'countries', ['country_code'], ['id'])

    # ### end Alembic commands ###

