"""Add address field to Place model

Revision ID: f5a1944f8775
Revises: 854a9f8eb969
Create Date: 2024-07-02 10:57:20.246911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a1944f8775'
down_revision = '854a9f8eb969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
